### ISSUE TITLE
Feature Request: Static path parameters

### ISSUE THREAD

**Issue by Scooter1337** [ap0nia/eden-query#12]
Hi! Interesting and useful library!

I was using 'eden-react-query' which is way more minimal than your implementation, but one thing that that library does better for my usecase is path parameters.

In 'eden-react-query' I can do this:
```
export function useSession() {
  return api.profile.settings.session.uuid({uuid: 'aaa'})
}
```

And then just do all my mutations on useSession().update.patch() etc etc

This makes it so that I only have to define the uuid once instead of everytime at a usequery / usemutation call.

**Comment by ap0nia** [comment]
Thanks for sharing! This is definitely a valid use-case.

I'm aware of this limitation and I can take a more in-depth look at addressing it. As I've noted [here](https://ap0nia.github.io/eden-query/eden-query/#notes), one of the reasons why this wasn't implemented from the start was that it would be difficult to integrate with Svelte's store-based reactivity.
