### ISSUE TITLE
Elysia edenPlugin: Type instantiation is excessively deep and possibly infinite

### ISSUE THREAD

**Issue by Extarys** [ap0nia/eden-query#49]
I had this issue since I first tried eden-query.

When trying to use `edenPlugin`, ts shows an error and all types are lost client-side for eden.

```js
import { Elysia, t } from "elysia";

import { edenPlugin } from "@ap0nia/eden-svelte-query";


const app = new Elysia()
	.use(edenPlugin({ batch: true }))
	.get("/test", () => {
		return "test"
	});
```

**Error**
```
Type instantiation is excessively deep and possibly infinite.ts(2589)
```

**Type**
```
(alias) edenPlugin<{
    batch: true;
}>(config: {
    batch: true;
}): <BasePath>(elysia: Elysia<BasePath, false, {
    decorator: {};
    store: {};
    derive: {};
    resolve: {};
}, {
    type: {};
    error: {};
}, {
    schema: {};
    macro: {};
    macroFn: {};
}, {}, {
    ...;
}, {
    ...;
}>) => Elysia<...>
```

**Versions**

I confirmed that everything is using latest released version.
```
@ap0nia/eden-svelte-query@"^1.2.0" from @repo/api-elysia@undefined
elysia@1.1.19
```

**Comment by ap0nia** [comment]
Could you share a reproduction repo?

**Comment by ap0nia** [comment]
You could try removing `node_modules` and any lock-files like `bun.lockb` before explicitly installing `bun install elysia@1.1.19`. Sometimes you can install an older version that still satisfies the `package.json` versions, and that's preserved in the lockfile.
