### ISSUE TITLE
Unable to resolve "elysia/error" from "node_modules/@ap0nia/eden/src/plugins/transform.ts"

### ISSUE THREAD

**Issue by azizsafudin** [ap0nia/eden-query#53]
Getting this error message when trying to use this package on a react native project:
```
Unable to resolve "elysia/error" from "node_modules/@ap0nia/eden/src/plugins/transform.ts"
```

Seems this import is not allowing me to use the library. Appreciate a resolution:

```
import { ElysiaCustomStatusResponse } from 'elysia/error'
```

Package.json:
```
"dependencies": {
	"@ap0nia/eden-react-query": "^1.2.1",
	"@elysiajs/eden": "^1.1.3",
	...
},
"devDependencies": {
	"elysia": "^1.1.20",
},
```

Also tried with `elysia@1.1.6` and `1.1.19`, both has the same error.

**Comment by ap0nia** [comment]
Would it be possible to provide a reproduction repository so I could see how it's being used in the project?

**Comment by azizsafudin** [comment]
> Would it be possible to provide a reproduction repository so I could see how it's being used in the project?

Here you go: https://github.com/azizsafudin/eden-query-repro

Thank you

**Comment by ap0nia** [comment]
Thank you!

My initial impression is that this might be addressable by configuring the bundler. `elysia/errors` is an export specified by the `exports` field in the package's `package.json`.

Documentation about enabling it could be found here:
https://github.com/expo/expo/issues/26926
https://reactnative.dev/blog/2023/06/21/package-exports-support

I've been trying to see if I could figure out a working configuration. But if nothing works, then I can try just comparing constructor names without importing the actual class...

**Comment by azizsafudin** [comment]
I guess that works?

After enabling  `unstable_enablePackageExports`, I get the following, which I assume is unrelated, but just another problem that got unblocked by resolving the previous issue as I can make this appear when I remove the offending import without enabling `unstable_enablePackageExports`.

```
Static class blocks are not enabled. Please add `@babel/plugin-transform-class-static-block` to your configuration.
  5672 | // src/index.ts
  5673 | import { TypeSystemPolicy as TypeSystemPolicy2 } from "@sinclair/typebox/system";
> 5674 | var Elysia = class _Elysia {
       |              ^
  5675 |   constructor(config = {}) {
  5676 |     this.server = null;
  5677 |     this.dependencies = {};
  ```
  
  Adding `@babel/plugin-transform-class-static-block` just breaks everything.

**Comment by ap0nia** [comment]
I also experienced this; I don't think clients should be importing objects from the `elysia` server package. I will try removing the `plugins` from the main import for `eden` to help with this.

I am still trying to figure out react-native setup.

**Comment by ap0nia** [comment]
Here's an example I put together for now https://github.com/ap0nia/eden-query/tree/52350f7cc41494919d1e4c6496481ddc206befdb/examples/react-native
